name: Example Workflow with Numos Test Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_code:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simulate testing
        run: echo "🚀 Simulating testing..."

  run_numos_tests:
    name: Trigger & Monitor AI Test Suite
    needs: lint_code
    runs-on: ubuntu-latest

    steps:
      - name: Trigger and Monitor Tests via Numos
        uses: numosai/numos-triggers@main
        with:
          test_suite_id: 'c819c4fc-12c4-4e97-9a0a-ff79fc8cf469'
          api_base_url: 'https://staging.api.numos.ai'

  deploy_app:
    name: Deploy Application
    needs: run_numos_tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Simulate Deployment
        run: echo "🚀 Deploying application..."